Update awake_start

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -1,6 +1,6 @@
 #!/bin/bash -eu
 
-if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) ]]
+if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) && ( -z "${TESLA_PRIVATE_KEY:+x}" ) ]]
 then
   log "Not keeping car awake."
   exit
@@ -9,6 +9,18 @@ fi
 function ping {
   while true
   do
+    if [[ ( -n "${TESLA_PRIVATE_KEY:+x}" ) ]]
+    # Use Tesla Ble to keep car awake
+    then
+      if timeout 10 /root/bin/tesla_ble_ping.py
+      then
+        sleep 90
+      else
+        log "Failed to contact car using Tesla Ble, retrying in 5s..."
+        sleep 5
+      fi
+    fi
+
     if [[ ( -n "${TESLA_REFRESH_TOKEN:+x}" ) ]]
     # Use Tesla API to keep car awake
     then
